info:
  app:
    name: My Company
    description: Microservice

spring:
  datasource:
    url: jdbc:mysql://mysql/dfid?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

